import { Controller, Get, Post, Param, Res, UseGuards } from '@nestjs/common';
import { Response } from 'express';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { DigestService, DigestData } from './digest.service';

function renderDigestHtml(digest: DigestData): string {
  const scoreColor = (s: number) => s >= 9 ? '#2D733E' : s >= 7 ? '#354B8C' : '#D93A2B';
  const npsColor = digest.npsScore >= 50 ? '#2D733E' : digest.npsScore >= 0 ? '#354B8C' : '#D93A2B';
  const periodStart = new Date(digest.periodStart).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  const periodEnd = new Date(digest.periodEnd).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PulseLoop Digest: ${digest.appName}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f0eeec; color: #1a1a2e; padding: 24px; }
  .container { max-width: 640px; margin: 0 auto; }
  .header { text-align: center; margin-bottom: 32px; }
  .header h1 { font-size: 24px; font-weight: 700; margin-bottom: 4px; }
  .header p { color: #666; font-size: 14px; }
  .card { background: white; border-radius: 12px; padding: 24px; margin-bottom: 16px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }
  .card h2 { font-size: 16px; font-weight: 600; margin-bottom: 16px; color: #354B8C; }
  .metrics { display: flex; gap: 16px; }
  .metric { flex: 1; text-align: center; }
  .metric .value { font-size: 32px; font-weight: 700; }
  .metric .label { font-size: 12px; color: #888; margin-top: 4px; }
  .tag-list { display: flex; flex-wrap: wrap; gap: 8px; }
  .tag { background: rgba(53,75,140,0.08); color: #354B8C; padding: 4px 12px; border-radius: 4px; font-size: 13px; }
  .tag .count { font-weight: 600; margin-left: 4px; }
  .action { display: flex; align-items: center; gap: 8px; padding: 8px 0; border-bottom: 1px solid #f0f0f0; }
  .action:last-child { border-bottom: none; }
  .action .check { color: #2D733E; font-size: 16px; }
  .action .text { font-size: 14px; }
  .action .action-tag { font-size: 11px; color: #888; background: #f5f5f5; padding: 2px 8px; border-radius: 3px; }
  .comment { padding: 12px 0; border-bottom: 1px solid #f0f0f0; }
  .comment:last-child { border-bottom: none; }
  .comment .score-badge { display: inline-block; font-size: 12px; font-weight: 600; padding: 2px 8px; border-radius: 4px; margin-right: 8px; }
  .comment .text { font-size: 14px; color: #333; line-height: 1.5; }
  .empty { text-align: center; color: #999; padding: 16px; font-size: 14px; }
  .footer { text-align: center; color: #999; font-size: 12px; margin-top: 24px; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>${digest.appName}</h1>
    <p>Weekly Digest: ${periodStart} - ${periodEnd}</p>
  </div>

  <div class="card">
    <h2>This Week's Numbers</h2>
    <div class="metrics">
      <div class="metric">
        <div class="value" style="color: ${scoreColor(Math.round(digest.averageScore))}">${digest.averageScore}</div>
        <div class="label">Avg Score</div>
      </div>
      <div class="metric">
        <div class="value" style="color: ${npsColor}">${digest.npsScore > 0 ? '+' : ''}${digest.npsScore}</div>
        <div class="label">NPS</div>
      </div>
      <div class="metric">
        <div class="value">${digest.totalResponses}</div>
        <div class="label">Responses</div>
      </div>
    </div>
  </div>

  ${digest.topTags.length > 0 ? `
  <div class="card">
    <h2>Top Tags</h2>
    <div class="tag-list">
      ${digest.topTags.map(t => `<span class="tag">${t.tag}<span class="count">(${t.count})</span></span>`).join('')}
    </div>
  </div>` : ''}

  ${digest.completedActions.length > 0 ? `
  <div class="card">
    <h2>You Said, We Did</h2>
    ${digest.completedActions.map(a => `
    <div class="action">
      <span class="check">&#10003;</span>
      <span class="text">${a.text}</span>
      ${a.tag ? `<span class="action-tag">${a.tag}</span>` : ''}
    </div>`).join('')}
  </div>` : ''}

  ${digest.recentComments.length > 0 ? `
  <div class="card">
    <h2>What People Said</h2>
    ${digest.recentComments.map(c => `
    <div class="comment">
      <span class="score-badge" style="background: ${scoreColor(c.score)}20; color: ${scoreColor(c.score)}">${c.score}/10</span>
      <span class="text">"${c.comment}"</span>
    </div>`).join('')}
  </div>` : ''}

  ${digest.totalResponses === 0 ? '<div class="card"><div class="empty">No feedback received this week.</div></div>' : ''}

  <div class="footer">
    Generated by PulseLoop on ${new Date(digest.generatedAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
  </div>
</div>
</body>
</html>`;
}

@ApiTags('digest')
@Controller('api/digest')
export class DigestController {
  constructor(private digestService: DigestService) {}

  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @Post(':appId/generate')
  async generate(@Param('appId') appId: string) {
    return this.digestService.generateDigest(appId);
  }

  @Get(':appId/latest')
  async getLatestHtml(@Param('appId') appId: string, @Res() res: Response) {
    let digest = this.digestService.getLatestDigest(appId);
    if (!digest) {
      digest = await this.digestService.generateDigest(appId);
    }
    res.setHeader('Content-Type', 'text/html');
    res.send(renderDigestHtml(digest));
  }

  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @Get(':appId/data')
  async getLatestData(@Param('appId') appId: string) {
    let digest = this.digestService.getLatestDigest(appId);
    if (!digest) {
      digest = await this.digestService.generateDigest(appId);
    }
    return digest;
  }
}
